version: '3.7'
services:
  # nginx:
  #   container_name: dev_web
  #   restart: on-failure
  #   image: nginx:1.19.8
  #   volumes:
  #     - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - static_volume:/app/static
  #   ports:
  #     - 81:80
  #   depends_on:
  #     - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/app
     - static_volume:/app/static
    ports:
      - 8080:8000
    depends_on:
     - db

    environment:
      - DEBUG=0
     
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - 5433:5432

    environment:
      - DB_PASSWORD=1234


volumes:
  static_volume:
  postgres_data: